name: Copy Shared Files
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Copy_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Data
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_data/PhantomListeners.json'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'blog'
          dst_path: '/_data/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'
          commit_message: 'Updating Phantom Data [Bot]'
